enclave-cc-deploy: Fix runtimeclass path
Instead of using `/runtimeclass/enclave-cc.yaml`, let's use the full
path for it `/opt/enclave-cc-artifacts/runtimeclass/enclave-cc.yaml`

This will fix the following error faced on the Operator CI side:
```
ubuntu@operator:~/operator$ kubectl -n confidential-containers-system logs cc-operator-daemon-install-j4fxn -c cc-runtime-install-pod
copying enclave-cc artifacts onto host
Add enclave-cc as a supported runtime for containerd
Configuration exists for plugins."io.containerd.grpc.v1.cri".containerd.runtimes.enclave-cc, overwriting
Creating the runtime classes
error: the path "/runtimeclass/enclave-cc.yaml" does not exist
```

Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>